name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Or any other branch from which you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ageless-accord-414413
        export_default_credentials: true

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/dwhtech:${{ github.sha }} .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/dwhtech:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy dwhtech \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/dwhtech:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated  

